
#ifndef _PROJECT_DEFS_H
#define _PROJECT_DEFS_H

#include <STC/15W4xxAS/SKDIP28.h>

#define CONSOLE_UART   UART1
#define CONSOLE_SPEED  57600UL
#define CONSOLE_PIN_CONFIG 0

#define HAL_UARTS 1
#define HAL_PCA_CHANNELS 1
#define BASIC_GPIO_HAL
#define UART_DEFAULT_BUFFER_SIZE 8

#define SUPPRESS_delay1us_WARNING

#endif // _PROJECT_DEFS_H
